apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: dbdump
  name: dbdump
spec:
  storageClassName: "nvme.r2"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
