apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mqdata
  name: mqdata
spec:
  storageClassName: "nvme.r2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
