apiVersion: v1
data:
  indexer.ini: |
    [database]
    dbname = musicbrainz_db
    host = db
    password = abc
    port = 5432
    user = abc

    [solr]
    uri = http://search:8983/solr
    batch_size = 200

    [sir]
    import_threads = 8
    index_limit = 200000
    live_index_batch_size = 100
    process_delay = 15
    query_batch_size = 5000
    wscompat = on

    [rabbitmq]
    host = mq
    user = sir
    password = sir
    vhost = /search-index-rebuilder
    prefetch_count = 350

    [sentry]
    dsn =
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: indexer
  name: indexer-cm0
