apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: solrdump
  name: solrdump
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
