apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: solrdata
  name: solrdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
